### ISSUE TITLE
Use the Raspberry Pi to trackball directly behind the hub and drive to it. Then intake it (guess).

### ISSUE THREAD

**Issue by srimanachanta** [Talon540Programming/RobotCode-v14#10]

**Comment by aryanmhaskar** [comment]
There is about a 0.2% chance we can do this as there is like 15 seconds of total meeting time between now and competition- we can keep this as our last lower priority.

**Comment by Spirit-Supreme** [comment]
k, i will make sure it is ready by districts though, one ball auto doesn't satisfy my ego @Bluewaves54

**Comment by srimanachanta** [comment]
Replaced with Pathweaver
