### ISSUE TITLE
Find integrated Encoder positions that constitute held wrist positions (both up and down)

### ISSUE THREAD

**Issue by srimanachanta** [Talon540Programming/RobotCode-v14#16]

**Comment by Spirit-Supreme** [comment]
We still need this for auto code so we don't run rollers when its not up.

**Comment by WAaron-500** [comment]
Hello I am a mysterious stranger... Have you considered asking mechanical/electrical/whoever is in charge of sensors to slap on a beam break or reed switch to detect when up or down.
